# Use official Bun image
FROM oven/bun:1.1-slim AS base

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json bun.lockb* ./

# Install dependencies
RUN bun install --frozen-lockfile --production

# Copy source code
COPY . .

# Build the application 
RUN bun run build

# Set environment variables
ARG PORT=8080
ARG ENVIRONMENT=production
ARG JWT_SECRET
ARG JWT_ACCESS_EXPIRY=1h
ARG JWT_REFRESH_EXPIRY=7d
ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID
ARG FIREBASE_MEASUREMENT_ID
ARG FIREBASE_SERVICE_ACCOUNT_TYPE
ARG FIREBASE_SERVICE_ACCOUNT_PROJECT_ID
ARG FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID
ARG FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY
ARG FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL
ARG FIREBASE_SERVICE_ACCOUNT_CLIENT_ID
ARG FIREBASE_SERVICE_ACCOUNT_AUTH_URI
ARG FIREBASE_SERVICE_ACCOUNT_TOKEN_URI
ARG FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL
ARG FIREBASE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL
ARG FIREBASE_SERVICE_ACCOUNT_UNIVERSE_DOMAIN
ARG CORS_ORIGIN
ARG FRONTEND_URL
ARG BACKEND_URL

# Set environment variables from build args
ENV PORT=${PORT}
ENV ENVIRONMENT=${ENVIRONMENT}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_ACCESS_EXPIRY=${JWT_ACCESS_EXPIRY}
ENV JWT_REFRESH_EXPIRY=${JWT_REFRESH_EXPIRY}
ENV FIREBASE_API_KEY=${FIREBASE_API_KEY}
ENV FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
ENV FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
ENV FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
ENV FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
ENV FIREBASE_APP_ID=${FIREBASE_APP_ID}
ENV FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
ENV FIREBASE_SERVICE_ACCOUNT_TYPE=${FIREBASE_SERVICE_ACCOUNT_TYPE}
ENV FIREBASE_SERVICE_ACCOUNT_PROJECT_ID=${FIREBASE_SERVICE_ACCOUNT_PROJECT_ID}
ENV FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID=${FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID}
ENV FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY=${FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY}
ENV FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL=${FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL}
ENV FIREBASE_SERVICE_ACCOUNT_CLIENT_ID=${FIREBASE_SERVICE_ACCOUNT_CLIENT_ID}
ENV FIREBASE_SERVICE_ACCOUNT_AUTH_URI=${FIREBASE_SERVICE_ACCOUNT_AUTH_URI}
ENV FIREBASE_SERVICE_ACCOUNT_TOKEN_URI=${FIREBASE_SERVICE_ACCOUNT_TOKEN_URI}
ENV FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL}
ENV FIREBASE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL=${FIREBASE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL}
ENV FIREBASE_SERVICE_ACCOUNT_UNIVERSE_DOMAIN=${FIREBASE_SERVICE_ACCOUNT_UNIVERSE_DOMAIN}
ENV CORS_ORIGIN=${CORS_ORIGIN}
ENV FRONTEND_URL=${FRONTEND_URL}
ENV BACKEND_URL=${BACKEND_URL}

# Expose port
EXPOSE 8080


# Start the application
CMD ["bun", "run", "start"]
